name: Java CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up node 20 
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build with Maven
      run: |
          cd backend-calculator
            ./mvnw clean spring-boot:run & 
           echo "waiting 5 seconds for the server to start"
           sleep 5 
           attempt_counter=0
           max_attempts=5
           until $(curl --output /dev/null --silent --head --fail http://localhost:8080/add); do
              if [ ${attempt_counter} -eq ${max_attempts} ];then
                echo "Max attempts reached"
                exit 1
              fi
          
              printf '.'
              attempt_counter=$(($attempt_counter+1))
              sleep 5
           done
           echo "sever ready for testing"
           npm install -g newman
           newman -v
           newman run src/test/java/com/example/integration/calculator.postman_collection.json
