name: Java CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up node 20 
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Build with Maven
      run: |
          cd backend-calculator
            mvn spring-boot:run & 
           echo "waiting 5 seconds for the server to start"
           sleep 10
           echo "sever ready for testing"
           npm install -g newman
           newman -v
           newman run src/Tests backend.postman_collection.json
