name: Run tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true

      - name: Wait for Backend to Start
        run: |
          echo "Waiting for backend to be available..."
          timeout 60s bash -c '
          while ! curl -s http://localhost:8080/api/calculator/add?a=1&b=2; do
            echo "Waiting for backend..."
            sleep 5
          done
          '
          echo "Backend is up!"

      - name: Install and Run Frontend Tests
        run: |
          cd frontend
          npm install
          cd tests
          npm install
          ../node_modules/.bin/mocha *.js

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/